# Generated by Django 4.0.5 on 2022-06-21 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='게시 종료'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='게시 시간'),
        ),
    ]
