# Generated by Django 4.0.4 on 2022-06-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_hobby_hobby_userprofile_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
    ]
